---
title: 'PH C240B: HW 2'
author: "Yue You"
output: 
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(survival)
library(dplyr)
library(doParallel)
library(mvtnorm)
```

## Problem 2

Let $(W,A,Y)$ be the observed data with distribution, $P_0 \in M$ nonparametric. Define the following parameter mapping for $P\in M: \Psi(P) = E_P[(1,1,W)\beta]$ where $\beta=\Psi^1(P)=\text{argmin}_{\gamma}E_P(Y - (1,A,W)\gamma)^2$.

(a) The empirical distribution, $\textbf{P}_n$, is the NPMLE for the true distribution. We use $\textbf{P}_n$ as a plug-in estimator, $\Psi(\textbf{P}_n)$, for the true parameter, $\Psi(P_0)$. This is called the NPMLE for $\Psi(P_0)$. Derive this estimator’s influence curve. You may derive the efficient influence curve, $D^*_{\Psi}(P)$ first and then your answer is $D^*_{\Psi}(\textbf{P}_n)$  This is a valid approach but not the only approach.

Because $\Psi(P)$ is a function of $\Psi^1(P)$ we first derive the efficient influence curve for $\Psi^1(P)=\beta=\text{argmin}_{\gamma}E_P(Y - (1,A,W)\gamma)^2$. First we need to compute the pathwise derivative (also let's assume that W is $d$-dimensional:

We can use the delta method to derive the efficient influence curve for this parameter mapping:

$D^*_{\Psi}(P) = \frac{d\Psi}{d \beta}D^*_\beta (P)(O)\\$
$= E_P(1,1,W)D^*_\beta (P)(O)$

Next we compute $D^*_\beta (P)(O)$:
$\because \Psi^{'}(P) = \beta = \text{argmin}_{\gamma}E_P(Y - (1,A,W)\gamma)^2\\$
$\therefore \beta\ satisfies\ \frac{d}{d\beta}\text{argmin}_{\gamma}E_{P}(Y - (1,A,W)\beta)^2 = 0_{d\times 1}\\$
$\Rightarrow 2[E_{P}(Y - (1,A,W)\beta)(1, A, W)^T] = 0_{d\times 1}\\$
$\Rightarrow E_{P}(Y - (1,A,W)\beta)(1, A, W)^T = 0_{d\times 1}...................(1)\\$

And $\because \Psi^{'}(P_\epsilon) = \beta = \text{argmin}_{\gamma}E_{P_\epsilon}(Y - (1,A,W)\gamma)^2\\$
$\therefore \beta_\epsilon\ satisfies\ \frac{d}{d\beta_\epsilon}\text{argmin}_{\gamma}E_{P_\epsilon}(Y - (1,A,W)\beta_\epsilon)^2 = 0_{d\times 1}\\$
$\Rightarrow 2[E_{P_\epsilon}(Y - (1,A,W)\beta_\epsilon)(1, A, W)^T] = 0_{d\times 1}\\$
$\Rightarrow E_{P_\epsilon}(Y - (1,A,W)\beta_\epsilon)(1, A, W)^T = 0_{d\times 1}....................(2)\\$
from (1)(2)$\therefore E_{P}(Y - (1,A,W)\beta)(1, A, W)^T - E_{P_\epsilon}(Y - (1,A,W)\beta_\epsilon)(1, A, W)^T = 0_{d\times 1}\\$
$\Rightarrow E_{P}(Y - (1,A,W)\beta)(1, A, W)^T - E_{P_\epsilon}(Y - (1,A,W)\beta)(1, A, W)^T \\$
$+  E_{P_\epsilon}(Y - (1,A,W)\beta)(1, A, W)^T - E_{P_\epsilon}(Y - (1,A,W)\beta_\epsilon)(1, A, W)^T = 0_{d\times 1}\\$
$\therefore E_{P_\epsilon}(Y - (1,A,W)\beta_\epsilon)(1, A, W)^T - E_{P_\epsilon}(Y - (1,A,W)\beta)(1, A, W)^T.......(3)\\$
$= E_{P}(Y - (1,A,W)\beta)(1, A, W)^T - E_{P_\epsilon}(Y - (1,A,W)\beta)(1, A, W)^T..........(4)\\$
$\because lim_{\epsilon \rightarrow 0}\frac{(4)}{\epsilon}\\$
$= E_{P_\epsilon}(Y - (1,A,W)\frac{\beta_\epsilon-\beta}{\epsilon})(1, A, W)^T\\$
$= lim_{\epsilon \rightarrow 0} E_{P_\epsilon} (1,A,W)^T(1,A,W)\frac{\beta_\epsilon-\beta}{\epsilon})\\$
$= E_{P_\epsilon} (1,A,W)^T(1,A,W)\frac{d \Psi^{'}(P_\epsilon)}{d\epsilon}|_{\epsilon = 0}.........(5)\\$
And $\because lim_{\epsilon \rightarrow 0}\frac{(3)}{\epsilon}\\$
$= lim_{\epsilon \rightarrow 0} \int (Y - (1,A,W))\beta(1,A,W)^T\frac{P_\epsilon(O)-P(O)}{\epsilon}dv(O)(\because P_\epsilon(O) = (1+\epsilon h)P(O))\\$
$= \int (Y - (1,A,W))\beta(1,A,W)^TS(O)P(O)dv(O)\\$
$= E_p[(Y-(1,A,W))\beta(1,A,W)^TS(O)].........(6)\\$
$\therefore (5) = (6)\\$
$\Rightarrow E_{P_\epsilon} (1,A,W)^T(1,A,W)\frac{d \Psi^{'}(P_\epsilon)}{d\epsilon}|_{\epsilon = 0}\\$
$= E_p[(Y-(1,A,W))\beta(1,A,W)^TS(O)]\\$
$\Rightarrow \frac{d \Psi^{'}(P_\epsilon)}{d\epsilon}|_{\epsilon = 0}\\$
$= [E_{P_\epsilon} (1,A,W)^T(1,A,W)]^{-1}E_p[(Y-(1,A,W))\beta(1,A,W)^TS(O)]\\$
$\Rightarrow D^*_\beta(P)(O) = [E_{P_\epsilon} (1,A,W)^T(1,A,W)]^{-1}E_p[(Y-(1,A,W))\beta(1,A,W)^T]\\$
$\Rightarrow IC = E_{P_n}(1,1,W)[E_{P_{n,\epsilon}} (1,A,W)^T(1,A,W)]^{-1}E_{p_n}[(Y-(1,A,W))\beta(1,A,W)^T]- \Psi(P)$

### Collaborators & Resources

Rachael Philips, Chris Kennedy, Tommy Carpenito
